RandomImageAPI/Models/IRepository.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;

namespace RandomImage.Models
{
    public interface IRepository
    {
        void SaveVote(Vote v);
        List<Vote> GetVotes(string id);

    }
}

RandomImageAPI/Models/PhotoInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RandomImage.Models
{
    public class PhotoInfo
    {
        public string LargeSquareThumbnailUrl { get; set; }
        public string LargeUrl { get; set; }
        public string PhotoId { get; set; }
        public string ThumbnailUrl { get; set; }
    }
}

RandomImageAPI/Models/Randomizer.cs
using System;
using FlickrNet;

namespace RandomImage.Models
{
    public class Randomizer
    {

        public static PhotoInfo GetPhoto()
        {
            const string myFlickrApiKey = "e6c196c0a47f3a94494c9b2fabfe764c";
            Flickr flickr = new Flickr(myFlickrApiKey);
            var options = new PhotoSearchOptions {Tags = "colorful", PerPage = 1000, Page = 1};
            PhotoCollection photos = flickr.PhotosSearch(options);
            Random r = new Random();
            int i = r.Next(0, photos.Count);
            var photo = photos[i];
            PhotoInfo photoInf = new PhotoInfo
            {
                LargeSquareThumbnailUrl = photo.LargeSquareThumbnailUrl,
                LargeUrl = photo.LargeUrl,
                PhotoId = photo.PhotoId,
                ThumbnailUrl = photo.ThumbnailUrl
            };
            return photoInf;
        }
    }
}

RandomImageAPI/Models/UserInfo.cs
namespace RandomImage.Models
{
    public class UserInfo
    {
        public string Name { get; set; }
        public string UserId { get; set; }
    }
}

RandomImageAPI/Models/Vote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;


namespace RandomImage.Models
{
    public class Vote
    {
        public int VoteId { get; set; } 
        public PhotoInfo Photo { get; set; }
        public UserInfo User { get; set; }
        public bool IsLike { get; set; }
    }


    public class VoteContext : DbContext
    {
        public DbSet<Vote> Votes { get; set; } 
    }

}

RandomImageAPI/Models/VoteDAL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RandomImage.Models
{
    public class VoteDAL:IRepository, IDisposable
    {
        public void SaveVote(Vote v)
        {
            using (var db = new VoteContext())
            {
                db.Votes.Add(v);
                db.SaveChanges();
            }
        }

        public List<Vote> GetVotes(string id)
        {
            if (String.IsNullOrEmpty(id))
                id = "1"; //reserved for test anonymus scenario

            List<Vote> lst = new List<Vote>();
            using (var db = new VoteContext())
            {
                lst = db.Votes.Where(v => v.User.UserId == id).OrderByDescending(v=>v.VoteId).ToList();
            }
            return lst;
        }

        public void Dispose()
        {
            
        }
    }
}

RandomImageAPI/Controllers/AuthController.cs
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using RandomImage.Models;

namespace RandomImage.Controllers
{
    public class AuthController : Controller
    {
        private const string AppId = "1787465338192564";
        private const string AppSecret = "a41c80ebc9a17a39981a064c045a9e1f";

        //Facerbook callback url (handler)
        string redirectUri = "http://localhost:3571/Auth/FacebookLoginCheck";

        public class FacebookToken
        {
            public string access_token;
            public string token_type;
            public string expires_in;
        }

        public class FacebookUser
        {
            public string name;
            public string id;
        }

        [HttpGet]
        public RedirectResult FacebookLogin()
        {
            return Redirect(string.Format("https://www.facebook.com/dialog/oauth?client_id={0}&redirect_uri={1}", AppId, redirectUri));
        }

        [HttpGet]
        public object FacebookLoginInfo()
        {
            return new { appId = AppId, authUrl = string.Format("https://www.facebook.com/dialog/oauth?client_id={0}&redirect_uri={1}", AppId, redirectUri) };
        }

       

        [HttpGet]
        public async Task<ActionResult> FacebookLoginCheck(string code)
        {
            string url = string.Format("https://graph.facebook.com/v2.5/oauth/access_token?client_id={0}&redirect_uri={1}&client_secret={2}&code={3}",
                AppId, redirectUri, AppSecret, code);
            HttpClient hc = new HttpClient();
            HttpResponseMessage resp = await hc.GetAsync(url);
            FacebookToken ft = await resp.Content.ReadAsAsync<FacebookToken>();
            url = "https://graph.facebook.com/v2.5/me?access_token=" + ft.access_token;
            resp = await hc.GetAsync(url);
            string s = await resp.Content.ReadAsStringAsync();
            FacebookUser fbu = (new JavaScriptSerializer()).Deserialize<FacebookUser>(s);

            UserInfo userInfo = new UserInfo { Name = fbu.name, UserId = fbu.id };
            Vote v = new Vote { Photo = null, User = userInfo };


            var json = JsonConvert.SerializeObject(userInfo);
            var userCookie = new HttpCookie("user", json);
            userCookie.Expires.AddDays(1);
            HttpContext.Response.Cookies.Add(userCookie);

            return RedirectToAction("Index", "Home", v);
            
        }



        [HttpGet]
        //[System.Web.Mvc.Route("api/auth/logout")]
        public ActionResult Logout()
        {
            var userCookie = new HttpCookie("user", "");
            HttpContext.Response.Cookies.Add(userCookie);

            Vote v = new Vote { Photo = null, User = null };
            return RedirectToAction("Index", "Home", v);
        }

    }
}

RandomImageAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Http.Results;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using FlickrNet;
using Newtonsoft.Json;
using RandomImage.Models;
using RedirectResult = System.Web.Mvc.RedirectResult;
using RedirectToRouteResult = System.Web.Mvc.RedirectToRouteResult;

namespace RandomImage.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            Models.PhotoInfo photoInf = Randomizer.GetPhoto();
            UserInfo userInfo = new UserInfo {Name = "Test", UserId = "1"};
            Vote v = new Vote {Photo = photoInf, User = userInfo};
            return View(v);
        }
        
        public ActionResult History(string id)
        {
            string userId = id;
            HttpCookie userInfoCookie = Request.Cookies.Get("user");

            if (userInfoCookie != null)
            {
                UserInfo user = (UserInfo)JsonConvert.DeserializeObject(userInfoCookie.Value, typeof(UserInfo));
                
                if(user!=null)
                    userId = user.UserId;
            }


            ViewBag.Title = "History Page";            
            List<Vote> lst = new List<Vote>();
            using (var rep = new VoteDAL())
            {
                lst = rep.GetVotes(userId);
            }
            return View("History", lst);                
        }


   

      

    }
}

RandomImageAPI/Controllers/ImageController.cs
using System.Web.Http;
using RandomImage.Models;

namespace RandomImage.Controllers
{
    
    public class ImageController : ApiController
    {
        
        [HttpGet]
        public Vote Get()
        {
            PhotoInfo photoInf = Randomizer.GetPhoto();
            UserInfo userInfo = new UserInfo { Name = "anonymous", UserId = "1" };
            Vote v = new Vote { Photo = photoInf, User = userInfo };
            return v;
        }
        
        [HttpPost]
        public string Vote(Vote vote)
        {
            using (var rep = new VoteDAL())
            {
                rep.SaveVote(vote);
            }
            return vote.IsLike ? "Liked" : "Disliked";
        }

     
       
    }
}

RandomImageAPI/Views/Home/History.cshtml
<div class="history-block">
  @{
      ViewBag.Title = "History";
      Layout = "~/Views/Shared/_Layout.cshtml";
    }

    @using RandomImage.Models
    @model List<RandomImage.Models.Vote>

    <h2>History</h2>

    @foreach (Vote v in Model)
    {

        <div class="@v.IsLike.ToString()"><a href="@v.Photo.LargeUrl"><img src="@v.Photo.LargeSquareThumbnailUrl" /></a></div>


    }  
</div>

RandomImageAPI/Views/Home/Index.cshtml
@model RandomImage.Models.Vote


        <h1>Random flickr image:</h1>
        
        <div class="imagewrapp">
            <img ng-src="{{imageurl}}"
                 ng-class="{'opacity' : whenLoading}"
                 class="current-image" />
            <img class="loader" src="~/Content/loader.gif" ng-show="whenLoading" />          
            
            <div class="message" ng-show="message" ng-bind="message"></div>
        </div>
        

<div class="settings">
    <div class="next-image">
        <i class="fa fa-refresh" aria-hidden="true" ng-click="GetNewImage()"></i>
    </div>
    <div class="votes">
        <div ng-click="DoVote(true)">
            <i class="fa fa-thumbs-up" aria-hidden="true"></i> Like
        </div>
        <div ng-click="DoVote(false)">
            <i class="fa fa-thumbs-down" aria-hidden="true"></i> Dislike
        </div>
        
    </div>    
</div>       

        


        
        @*@Html.HiddenFor(m => m.User.UserId)
        @Html.HiddenFor(m => m.User.Name)

        @using (Html.BeginForm("vote", "api/image", FormMethod.Post))
        {
 
            @Html.HiddenFor(m => m.Photo.LargeSquareThumbnailUrl)
            @Html.HiddenFor(m => m.Photo.LargeUrl)
            @Html.HiddenFor(m => m.Photo.PhotoId)
            @Html.HiddenFor(m => m.Photo.ThumbnailUrl)

            <input type="hidden" name="IsLike" id="IsLike" value="true" />
            <input type="submit" value="Like" />
        }
               
        
        @using (Html.BeginForm("Dislike", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            @Html.HiddenFor(m => m.Photo.LargeSquareThumbnailUrl)
            @Html.HiddenFor(m => m.Photo.LargeUrl)
            @Html.HiddenFor(m => m.Photo.PhotoId)
            @Html.HiddenFor(m => m.Photo.ThumbnailUrl)

            <input type="hidden" name="IsLike" id="IsLike" value="false" />
            <input type="submit" value="Dislike" />
        }*@

RandomImageAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    @Styles.Render("~/Content/css")
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.4/angular.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/restangular/1.3.1/restangular.min.js"></script>
    
    <script src="~/Scripts/app.js"></script>
    
</head>
<body ng-app="app">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("History", "History", "Home", new { area = "" }, null)</li>

                    <li ng-if="UserInfo.Name == 'anonymous'">@Html.ActionLink("Sign in", "FacebookLogin", "Auth", new { area = "" }, null)</li>
                    <li ng-if="UserInfo.Name != 'anonymous'" title="Log out" >@Html.ActionLink("{{UserInfo.Name}}", "Logout", "Auth")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>